apiVersion: v1
kind: ImageStream
metadata:
  name: openshift-preflight
  namespace: ci
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/opdev/preflight:latest
    importPolicy:
      scheduled: false
